version: "3.8"
services:
  elk:
    image: sebp/elk:780
    deploy:
      resources:
        reservations:
          memory: 4G
    restart: always
    volumes:
      - ./logstash/conf.d:/etc/logstash/conf.d:ro
      - elk:/var/lib/elasticsearch
    networks: 
      shared-net:
        aliases: 
          - kibana
          - logstash
          - elasticsearch
  nginx-app-protect-simple-site:
    build:
      context: ./nginx
      dockerfile: Dockerfile.simple-site
    restart: always
    networks: 
      shared-net:
        aliases: 
          - nginx
    ports:
      - "80:80" #app protect
      - "81:81" #kibana
      - "443:443"
      - "8080:8080" #status api
networks: 
  shared-net:
    external: false
    name: shared-net
volumes:
  elk:
